print('\033[32;1m===== Tabuada de Multiplicação =====\033[32m')
n = int(input('\033[31mDigte um número: \033[m'))
tab = int(1)
print(f'\033[34m|| {n} X {tab} = {n*tab:^3}  ||')
print(f'|| {n} X {tab+1} = {n*(tab+1):^3}  ||')
print(f'|| {n} X {tab+2} = {n*(tab+2):^3}  ||')
print(f'|| {n} X {tab+3} = {n*(tab+3):^3}  ||')
print(f'|| {n} X {tab+4} = {n*(tab+4):^3}  ||')
print(f'|| {n} X {tab+5} = {n*(tab+5):^3}  ||')
print(f'|| {n} X {tab+6} = {n*(tab+6):^3}  ||')
print(f'|| {n} X {tab+7} = {n*(tab+7):^3}  ||')
print(f'|| {n} X {tab+8} = {n*(tab+8):^3}  ||')
print(f'|| {n} X {tab+9} = {n*(tab+9):^3} ||')

