print('===== Tabuada de Multiplicação =====')
n = int(input('Digte um número: '))
tab = int(1)
print(f'|| {n} X {tab} = {n*tab:^3}  ||')
print(f'|| {n} X {tab+1} = {n*(tab+1):^3}  ||')
print(f'|| {n} X {tab+2} = {n*(tab+2):^3}  ||')
print(f'|| {n} X {tab+3} = {n*(tab+3):^3}  ||')
print(f'|| {n} X {tab+4} = {n*(tab+4):^3}  ||')
print(f'|| {n} X {tab+5} = {n*(tab+5):^3}  ||')
print(f'|| {n} X {tab+6} = {n*(tab+6):^3}  ||')
print(f'|| {n} X {tab+7} = {n*(tab+7):^3}  ||')
print(f'|| {n} X {tab+8} = {n*(tab+8):^3}  ||')
print(f'|| {n} X {tab+9} = {n*(tab+9):^3} ||')
