print('==== Quantos dolares você pode comprar ====')
real = float(input('Quantos reais você tem? R$ '))
dolar = float(5.84)
print(f'Você pode comprar US${real/dolar:.2f} ')
print('>>> Dolar = 5,84 (05/2020)')
